#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONSubscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONSubscriptTests = [
        ("testIntSubscript", testIntSubscript),
        ("testStringSubscript", testStringSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONSubscriptTests.__allTests__CoreJSONSubscriptTests),
    ]
}
#endif
