#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONPointerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONPointerTests = [
        ("testArrayAppend", testArrayAppend),
        ("testArrayIndex", testArrayIndex),
        ("testCreationOfArray", testCreationOfArray),
        ("testCreationOfArrayWithEndIndex", testCreationOfArrayWithEndIndex),
        ("testCreationOfObject", testCreationOfObject),
        ("testEmptyArrayIndex", testEmptyArrayIndex),
        ("testEmptyKey", testEmptyKey),
        ("testEmptyKeyOnString", testEmptyKeyOnString),
        ("testEmptyPointer", testEmptyPointer),
        ("testEscapeOrder", testEscapeOrder),
        ("testKeyOnArray", testKeyOnArray),
        ("testLastPathComponent", testLastPathComponent),
        ("testLeadingZeroArrayIndex", testLeadingZeroArrayIndex),
        ("testLiteral", testLiteral),
        ("testMutateNested", testMutateNested),
        ("testNonEmptyKey", testNonEmptyKey),
        ("testNonExistingArrayIndex", testNonExistingArrayIndex),
        ("testPathComponents", testPathComponents),
        ("testResetNested", testResetNested),
        ("testResetNonExistingPath", testResetNonExistingPath),
        ("testResetOnString", testResetOnString),
        ("testRfcExamples", testRfcExamples),
        ("testSetIndexOutOfBounds", testSetIndexOutOfBounds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONPointerTests.__allTests__CoreJSONPointerTests),
    ]
}
#endif
