#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONLiteralsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONLiteralsTests = [
        ("testArrayLiteral", testArrayLiteral),
        ("testBooleanLiteral", testBooleanLiteral),
        ("testDictionaryLiteral", testDictionaryLiteral),
        ("testFloatLiteral", testFloatLiteral),
        ("testIntegerLiteral", testIntegerLiteral),
        ("testNilLiteral", testNilLiteral),
        ("testStringLiteral", testStringLiteral),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONLiteralsTests.__allTests__CoreJSONLiteralsTests),
    ]
}
#endif
