#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONTests = [
        ("testEqualsArray", testEqualsArray),
        ("testEqualsBool", testEqualsBool),
        ("testEqualsDouble", testEqualsDouble),
        ("testEqualsFloat", testEqualsFloat),
        ("testEqualsInt", testEqualsInt),
        ("testEqualsInt64", testEqualsInt64),
        ("testEqualsNull", testEqualsNull),
        ("testEqualsNumber", testEqualsNumber),
        ("testEqualsObject", testEqualsObject),
        ("testEqualsString", testEqualsString),
        ("testEqualsUInt", testEqualsUInt),
        ("testEqualsUInt64", testEqualsUInt64),
        ("testHashArray", testHashArray),
        ("testHashBool", testHashBool),
        ("testHashDouble", testHashDouble),
        ("testHashFloat", testHashFloat),
        ("testHashInt", testHashInt),
        ("testHashInt64", testHashInt64),
        ("testHashNull", testHashNull),
        ("testHashNumber", testHashNumber),
        ("testHashObject", testHashObject),
        ("testHashString", testHashString),
        ("testHashUInt", testHashUInt),
        ("testHashUInt64", testHashUInt64),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONTests.__allTests__CoreJSONTests),
    ]
}
#endif
