#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONFromFoundationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONFromFoundationTests = [
        ("testBoolFalse", testBoolFalse),
        ("testBoolTrue", testBoolTrue),
        ("testDouble", testDouble),
        ("testFloat", testFloat),
        ("testFloatNumber", testFloatNumber),
        ("testInt64", testInt64),
        ("testInt64Number", testInt64Number),
        ("testInt", testInt),
        ("testJSONBoolFalse", testJSONBoolFalse),
        ("testJSONBoolTrue", testJSONBoolTrue),
        ("testJSONDouble", testJSONDouble),
        ("testJSONEmptyArray", testJSONEmptyArray),
        ("testJSONEmptyObject", testJSONEmptyObject),
        ("testJSONInt", testJSONInt),
        ("testJSONIntArray", testJSONIntArray),
        ("testJSONIntExponential", testJSONIntExponential),
        ("testJSONIntNegativeExponential", testJSONIntNegativeExponential),
        ("testJSONNull", testJSONNull),
        ("testJSONNullArray", testJSONNullArray),
        ("testJSONObject", testJSONObject),
        ("testJSONOptionalStringArray", testJSONOptionalStringArray),
        ("testJSONString", testJSONString),
        ("testNil", testNil),
        ("testNonNilOptional", testNonNilOptional),
        ("testUInt64", testUInt64),
        ("testUInt64Number", testUInt64Number),
        ("testUInt", testUInt),
        ("testUnsupported", testUnsupported),
    ]
}

extension CoreJSONToFoundationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONToFoundationTests = [
        ("testArrayWithString", testArrayWithString),
        ("testBoolFalse", testBoolFalse),
        ("testBoolTrue", testBoolTrue),
        ("testDouble", testDouble),
        ("testEmptyArray", testEmptyArray),
        ("testEmptyObject", testEmptyObject),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testInt64", testInt64),
        ("testNull", testNull),
        ("testObjectWithString", testObjectWithString),
        ("testString", testString),
        ("testUInt", testUInt),
        ("testUInt64", testUInt64),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONFromFoundationTests.__allTests__CoreJSONFromFoundationTests),
        testCase(CoreJSONToFoundationTests.__allTests__CoreJSONToFoundationTests),
    ]
}
#endif
