#if !canImport(ObjectiveC)
import XCTest

extension CoreJSONConvenienceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreJSONConvenienceTests = [
        ("testArrayValue", testArrayValue),
        ("testBoolValue", testBoolValue),
        ("testDoubleValue", testDoubleValue),
        ("testFloatValue", testFloatValue),
        ("testIntValue", testIntValue),
        ("testIsArray", testIsArray),
        ("testIsBool", testIsBool),
        ("testIsDouble", testIsDouble),
        ("testIsFloat", testIsFloat),
        ("testIsInt", testIsInt),
        ("testIsInt64", testIsInt64),
        ("testIsNull", testIsNull),
        ("testIsNumber", testIsNumber),
        ("testIsObject", testIsObject),
        ("testIsString", testIsString),
        ("testIsUInt", testIsUInt),
        ("testIsUInt64", testIsUInt64),
        ("testObjectValue", testObjectValue),
        ("testStringValue", testStringValue),
        ("testUIntValue", testUIntValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoreJSONConvenienceTests.__allTests__CoreJSONConvenienceTests),
    ]
}
#endif
